<?php
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/../../includes/tie/bootstrap.php';
require_once __DIR__ . '/../../includes/tie/Api.php';

UthengaTieApi::respond([
    'success' => true,
    'service' => UthengaTieConfig::string('TIE_SERVICE_NAME', 'travel-intelligence-engine'),
    'version' => UthengaTieConfig::string('TIE_API_VERSION', 'v1'),
    'endpoints' => [
        'health' => 'api/tie/health.php',
        'frontend_bootstrap' => 'api/tie/frontend/bootstrap.php',
        'context' => 'api/tie/context.php',
        'context_build' => 'api/tie/context/build.php',
        'trips' => 'api/tie/trips.php',
        'recommendations' => 'api/tie/recommendations.php',
        'conversation_chat' => 'api/tie/conversation/chat.php',
        'conversation_assistant' => 'api/tie/conversation/assistant.php',
        'ai_capability' => 'api/tie/ai/capability.php',
        'plans_create' => 'api/tie/plans/create.php',
        'plans_view' => 'api/tie/plans/view.php',
        'plans_update' => 'api/tie/plans/update.php',
        'plans_validate' => 'api/tie/plans/validate.php',
        'plans_approve' => 'api/tie/plans/approve.php',
        'payment_options' => 'api/tie/payments/options.php',
        'plans_export' => 'api/tie/plans/export.php',
        'booking_validate' => 'api/tie/bookings/validate.php',
        'booking_execute' => 'api/tie/bookings/execute.php',
        'booking_cancel' => 'api/tie/bookings/cancel.php',
        'booking_status' => 'api/tie/bookings/status.php',
        'services' => 'api/tie/services.php',
        'vendors' => 'api/tie/vendors.php',
        'categories' => 'api/tie/categories.php',
        'availability_validate' => 'api/tie/availability/validate.php',
        'location_context' => 'api/tie/location/context.php',
        'location_permission' => 'api/tie/location/permission.php',
        'location_nearby' => 'api/tie/location/nearby.php',
        'vendor_coordinate' => 'api/tie/location/vendor-coordinate.php',
        'vendor_coordinate_verify' => 'api/tie/location/vendor-coordinate-verify.php',
        'vendor_coordinate_import' => 'api/tie/location/vendor-coordinate-import.php',
        'quick_travel_action' => 'api/tie/coordination/action.php',
        'quick_travel_discover' => 'api/tie/coordination/discover.php',
        'quick_travel_session' => 'api/tie/coordination/session.php',
        'quick_travel_vendor_queue' => 'api/tie/coordination/vendor-queue.php',
        'quick_travel_call_signals' => 'api/tie/coordination/call-signals.php',
        'quick_travel_departures' => 'api/tie/coordination/departures.php',
        'quick_travel_departure' => 'api/tie/coordination/departure.php',
        'quick_travel_history' => 'api/tie/coordination/history.php',
        'vendor_profiles' => 'api/tie/vendor/profiles.php',
        'trip_dashboard' => 'api/tie/trip/dashboard.php',
        'trip_list' => 'api/tie/trip/list.php',
        'trip_detail' => 'api/tie/trip/detail.php',
        'trip_action' => 'api/tie/trip/action.php',
        'passenger_summary' => 'api/tie/passenger/summary.php',
        'passenger_list' => 'api/tie/passenger/list.php',
        'passenger_detail' => 'api/tie/passenger/detail.php',
        'passenger_action' => 'api/tie/passenger/action.php',
        'message_conversations' => 'api/tie/message/conversations.php',
        'message_notifications' => 'api/tie/message/notifications.php',
        'message_action' => 'api/tie/message/action.php',
        'earnings_summary' => 'api/tie/earnings/summary.php',
        'earnings_trend' => 'api/tie/earnings/trend.php',
        'earnings_transactions' => 'api/tie/earnings/transactions.php',
        'earnings_goal' => 'api/tie/earnings/goal.php',
        'earnings_action' => 'api/tie/earnings/action.php',
        'vehicle_overview' => 'api/tie/vehicle/overview.php',
        'vehicle_action' => 'api/tie/vehicle/action.php',
        'schedule_overview' => 'api/tie/schedule/overview.php',
        'schedule_action' => 'api/tie/schedule/action.php',
        'reports_report' => 'api/tie/reports/report.php',
        'driver_settings_overview' => 'api/tie/driver-settings/overview.php',
        'driver_settings_action' => 'api/tie/driver-settings/action.php',
        'transport_payment_start' => 'api/tie/transport-payment/start.php',
        'transport_payment_status' => 'api/tie/transport-payment/status.php',
        'transport_payment_cash' => 'api/tie/transport-payment/cash.php',
        'transport_payment_ledger' => 'api/tie/transport-payment/ledger.php',
        'transport_payment_webhook' => 'api/tie/transport-payment/webhook.php',
    ],
]);
