<?php
/** TIE's explicit internal composition root. */
require_once __DIR__ . '/Config.php';
require_once __DIR__ . '/Error.php';
require_once __DIR__ . '/Contracts.php';
require_once __DIR__ . '/Query.php';
require_once __DIR__ . '/Availability.php';
require_once __DIR__ . '/Providers.php';
require_once __DIR__ . '/Location.php';
require_once __DIR__ . '/Services.php';
require_once __DIR__ . '/Budget.php';
require_once __DIR__ . '/Conflict.php';
require_once __DIR__ . '/Context.php';
require_once __DIR__ . '/Recommendation.php';
require_once __DIR__ . '/Ai.php';
require_once __DIR__ . '/Planning.php';
require_once __DIR__ . '/Booking.php';
require_once __DIR__ . '/Inventory.php';
require_once __DIR__ . '/BookingCommit.php';
require_once __DIR__ . '/Payment.php';
require_once __DIR__ . '/Journey.php';
require_once __DIR__ . '/Notifications.php';
require_once __DIR__ . '/Coordination.php';
require_once __DIR__ . '/VendorProfiles.php';
require_once __DIR__ . '/Accommodation.php';
require_once __DIR__ . '/AccommodationFinance.php';
require_once __DIR__ . '/AccommodationPropertyWorkspace.php';
require_once __DIR__ . '/Observability.php';
require_once __DIR__ . '/Kernel.php';
